In [1]:
import pandas as pd

In [9]:
data = pd.read_csv('Motorcycle-Database-by-Teoalida (1).csv')

In [24]:
data.head(2)

,page_url,image_url,make,model,year_of_launch,category,rating,price_as_new_msrp,displacement_cm,engine_type,...,oil_capacity_litres,color_options,starter,instruments,electrical,light,carrying_capacity,factory_warranty,comments,modifications_compared_to_previous_model
0,https://bikez.com/motorcycles/bmw_k_1_1993.php,https://bikez.com/pictures/bmw/1993/k 1.jpg,BMW,BMW K 1,1993,Unspecified category,67.6 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,
1,https://bikez.com/motorcycles/bmw_k_1_1992.php,https://bikez.com/pictures/bmw/1992/k 1.jpg,BMW,BMW K 1,1992,Sport touring,69.2 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,

In [25]:
data = data.fillna(' ')
data.head(5)

,page_url,image_url,make,model,year_of_launch,category,rating,price_as_new_msrp,displacement_cm,engine_type,...,oil_capacity_litres,color_options,starter,instruments,electrical,light,carrying_capacity,factory_warranty,comments,modifications_compared_to_previous_model
0,https://bikez.com/motorcycles/bmw_k_1_1993.php,https://bikez.com/pictures/bmw/1993/k 1.jpg,BMW,BMW K 1,1993,Unspecified category,67.6 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,
1,https://bikez.com/motorcycles/bmw_k_1_1992.php,https://bikez.com/pictures/bmw/1992/k 1.jpg,BMW,BMW K 1,1992,Sport touring,69.2 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,
2,https://bikez.com/motorcycles/bmw_k_1_1991.php,https://bikez.com/pictures/bmw/1991/k 1.jpg,BMW,BMW K 1,1991,Allround,71.7 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,
3,https://bikez.com/motorcycles/bmw_k_1_1990.php,https://bikez.com/pictures/bmw/1990/k 1.jpg,BMW,BMW K 1,1990,Classic,67.4 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,
4,https://bikez.com/motorcycles/bmw_k_1_1989.php,https://bikez.com/pictures/bmw/1989/k 1.jpg,BMW,BMW K 1,1989,Sport touring,65.7 out of 100. Show full rating and compare ...,,987.0,,...,,,,,,,,,,

In [11]:
import pymysql

In [28]:
# Connect to the database
connection = pymysql.connect(host='localhost',
                         user='teoalida',
                         password='Mutex@321*#',
                         db='mototrip_db')

# create cursor
cursor=connection.cursor()

In [18]:
cols = "`,`".join([str(i) for i in data.columns.tolist()])

In [19]:
cols

'page_url`,`image_url`,`make`,`model`,`year_of_launch`,`category`,`rating`,`price_as_new_msrp`,`displacement_cm`,`engine_type`,`engine_details`,`power_ps`,`power_rpm`,`torque_nm`,`torque_rpm`,`top_speed_kmph`,`14_mil_sec`,`0_100_kmh_sec`,`60-140_kmh_highest_gear_sec`,`max_rpm`,`compression`,`bore_x_stroke_mm`,`valves_per_cylinder`,`fuel_system`,`fuel_control`,`ignition`,`lubrication_system`,`cooling_system`,`gearbox`,`transmission_type_final_drive`,`clutch`,`driveline`,`fuel_consumption_litres__100_km`,`greenhouse_gases_co2_gkm`,`emission_details`,`exhaust_system`,`frame_type`,`rake_fork_angle`,`trail`,`front_suspension`,`front_wheel_travel_mm`,`rear_suspension`,`rear_wheel_travel_mm`,`front_tyre`,`rear_tyre`,`front_brakes`,`front_brakes_diameter_mm`,`rear_brakes`,`rear_brakes_diameter_mm`,`wheels`,`seat`,`dry_weight_kg`,`weight_incl_oil_gas_etc_kg`,`powerweight_ratio_hpkgp`,`seat_height_mm`,`alternate_seat_height_mm`,`front_percentage_of_weight`,`rear_percentage_of_weight`,`overall_height_mm`,`overall_length_mm`,`overall_width_mm`,`ground_clearance_mm`,`wheelbase_mm`,`fuel_capacity_litres`,`reserve_fuel_capacity_litres`,`oil_capacity_litres`,`color_options`,`starter`,`instruments`,`electrical`,`light`,`carrying_capacity`,`factory_warranty`,`comments`,`modifications_compared_to_previous_model'

In [21]:
# # Insert DataFrame recrds one by one.
# for i,row in data.iterrows():
#     sql = "INSERT INTO `book_details` (`" +cols + "`) VALUES (" + "%s,"*(len(row)-1) + "%s)"
#     cursor.execute(sql, tuple(row))

#     # the connection is not autocommitted by default, so we must commit to save our changes
#     connection.commit()

In [31]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

In [32]:
sqlEngine       = create_engine('mysql+pymysql://teoalida:Mutex@321*#@127.0.0.1/mototrip_db', pool_recycle=3600)
dbConnection    = sqlEngine.connect()

In [22]:
tableName = 'mototrip_details'

In [33]:
try:
    frame = data.to_sql(tableName, dbConnection, if_exists='fail');

except ValueError as vx:
    print(vx)

except Exception as ex:
    print(ex)

else:
    print("Table %s created successfully."%tableName);   


dbConnection.close()

Table mototrip_details created successfully.